require("dotenv").config();

const mongoose =
  require("mongoose");

const connectDB =
  require("../config/db");

const FkWebRawEvent =
  require(
    "../attendance/fkwebRawEvent.model"
  );

/* =========================================================
   REAL DEVICE
========================================================= */

const DEVICE_ID =
  String(
    process.env
      .FKWEB_REAL_DEVICE_ID ||
      "RSS20241199635"
  ).trim();

/* =========================================================
   MAIN
========================================================= */

const run =
  async () => {
    try {
      console.log(
        "============================================================"
      );

      console.log(
        "CLEAN REALTIME FKWEB DEMO DATA"
      );

      console.log(
        "============================================================"
      );

      await connectDB();

      console.log(
        "✅ MongoDB connected"
      );

      /* =====================================================
         BEFORE
      ===================================================== */

      const totalBefore =
        await FkWebRawEvent
          .countDocuments({
            deviceId:
              DEVICE_ID,
          });

      const punchBefore =
        await FkWebRawEvent
          .countDocuments({
            deviceId:
              DEVICE_ID,

            eventType:
              "PUNCH",
          });

      const enrollmentBefore =
        await FkWebRawEvent
          .countDocuments({
            deviceId:
              DEVICE_ID,

            eventType:
              "ENROLLMENT",
          });

      console.log(
        "\nBEFORE CLEANUP"
      );

      console.log({
        total:
          totalBefore,

        punches:
          punchBefore,

        enrollments:
          enrollmentBefore,
      });

      /* =====================================================
         DELETE IMPORTED / FAKE PUNCHES

         This removes anything generated by the old demo
         import script.
      ===================================================== */

      const fakePunchResult =
        await FkWebRawEvent
          .deleteMany({
            deviceId:
              DEVICE_ID,

            eventType:
              "PUNCH",

            $or: [
              {
                recordId: {
                  $regex:
                    /^IMPORTED-/i,
                },
              },

              {
                uniqueEventKey: {
                  $regex:
                    /:PUNCH:IMPORTED:/i,
                },
              },

              {
                "rawPayload.importedForDemo":
                  true,
              },

              {
                "rawPayload.source": {
                  $regex:
                    /Captured earlier from Realtime S362 terminal/i,
                },
              },
            ],
          });

      console.log(
        `✅ Removed fake/imported punches: ${fakePunchResult.deletedCount}`
      );

      /* =====================================================
         DELETE IMPORTED ENROLLMENT SNAPSHOTS

         These were created by the old script, not received
         live by the current controller.

         Real enrollment events received from the machine
         later will be saved again automatically.
      ===================================================== */

      const fakeEnrollmentResult =
        await FkWebRawEvent
          .deleteMany({
            deviceId:
              DEVICE_ID,

            eventType:
              "ENROLLMENT",

            "rawPayload.source": {
              $regex:
                /Captured from Realtime S362 FKWeb terminal/i,
            },
          });

      console.log(
        `✅ Removed imported enrollment rows: ${fakeEnrollmentResult.deletedCount}`
      );

      /* =====================================================
         ALSO REMOVE TEST DEVICE COMPLETELY
      ===================================================== */

      const testResult =
        await FkWebRawEvent
          .deleteMany({
            deviceId:
              "TEST_DEVICE",
          });

      console.log(
        `✅ Removed TEST_DEVICE rows: ${testResult.deletedCount}`
      );

      /* =====================================================
         AFTER
      ===================================================== */

      const remainingPunches =
        await FkWebRawEvent
          .find({
            deviceId:
              DEVICE_ID,

            eventType:
              "PUNCH",
          })
          .sort({
            eventTime:
              1,
          })
          .lean();

      console.log(
        "\nGENUINE PUNCHES REMAINING"
      );

      if (
        !remainingPunches.length
      ) {
        console.log(
          "No genuine punches currently stored."
        );
      } else {
        remainingPunches
          .forEach(
            (
              punch
            ) => {
              console.log({
                biometricCode:
                  punch.biometricCode,

                employeeName:
                  punch.employeeName,

                eventTime:
                  punch.eventTime,

                recordId:
                  punch.recordId,

                deviceId:
                  punch.deviceId,
              });
            }
          );
      }

      console.log(
        "\n============================================================"
      );

      console.log(
        "✅ CLEANUP COMPLETE"
      );

      console.log(
        "============================================================"
      );
    } catch (
      error
    ) {
      console.error(
        "❌ Cleanup failed:",
        error
      );

      process.exitCode =
        1;
    } finally {
      await mongoose
        .connection
        .close();

      console.log(
        "MongoDB disconnected."
      );
    }
  };

run();