name: Deploy Backend to VPS

on:
  push:
    branches:
      - main
    paths:
      - "BACKEND/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy SE-RMS Backend
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            /var/www/SE-RMS/deploy-backend.sh